<a href="https://colab.research.google.com/github/Anshad-Aziz/technical-training/blob/main/Youtube_Spam_Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [128]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import cross_val_score

In [129]:
df=pd.read_csv('Youtube02-KatyPerry.csv')
df.head()

COMMENT_ID        AUTHOR                 DATE  \
0      z12pgdhovmrktzm3i23es5d5junftft3f   lekanaVEVO1  2014-07-22T15:27:50   
1    z13yx345uxepetggz04ci5rjcxeohzlrtf4      Pyunghee  2014-07-27T01:57:16   
2  z12lsjvi3wa5x1vwh04cibeaqnzrevxajw00k    Erica Ross  2014-07-27T02:51:43   
3    z13jcjuovxbwfr0ge04cev2ipsjdfdurwck  Aviel Haimov  2014-08-01T12:27:48   
4  z13qybua2yfydzxzj04cgfpqdt2syfx53ms0k    John Bello  2014-08-01T21:04:03   

                                             CONTENT  CLASS  
0  i love this so much. AND also I Generate Free ...      1  
1  http://www.billboard.com/articles/columns/pop-...      1  
2  Hey guys! Please join me in my fight to help a...      1  
3  http://psnboss.com/?ref=2tGgp3pV6L this is the...      1  
4  Hey everyone. Watch this trailer!!!!!!!!  http...      1

In [130]:
df.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 350 entries, 0 to 349
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   COMMENT_ID  350 non-null    object
 1   AUTHOR      350 non-null    object
 2   DATE        350 non-null    object
 3   CONTENT     350 non-null    object
 4   CLASS       350 non-null    int64 
dtypes: int64(1), object(4)
memory usage: 13.8+ KB


In [131]:
df.isnull().sum()

COMMENT_ID    0
AUTHOR        0
DATE          0
CONTENT       0
CLASS         0
dtype: int64

In [132]:
data=df[['CONTENT','CLASS']]
data.head()

CONTENT  CLASS
0  i love this so much. AND also I Generate Free ...      1
1  http://www.billboard.com/articles/columns/pop-...      1
2  Hey guys! Please join me in my fight to help a...      1
3  http://psnboss.com/?ref=2tGgp3pV6L this is the...      1
4  Hey everyone. Watch this trailer!!!!!!!!  http...      1

In [133]:
len(data)
len(data.query('CLASS==1'))
len(data.query('CLASS==0'))

175

In [134]:
fracdata=data.sample(frac=1)

In [135]:
train=fracdata.sample(frac=0.75,random_state=26)
test=data.drop(train.index)

In [136]:
x_train=np.array(train['CONTENT'])
y_train=np.array(train['CLASS'])

In [137]:
count_vectorizer=CountVectorizer()
X_train=count_vectorizer.fit_transform(x_train)

In [138]:
print('\nDimensions of training data:',X_train.shape)


Dimensions of training data: (262, 1472)


In [139]:
tfidf=TfidfTransformer()
train_tfidf=tfidf.fit_transform(X_train)
classifier=MultinomialNB().fit(train_tfidf,y_train)

In [140]:
scores=cross_val_score(classifier,X_train,y_train,cv=5)
scores

array([0.90566038, 0.86792453, 1.        , 0.96153846, 0.92307692])

In [141]:
scores2=cross_val_score(classifier,X_train,y_train)
print("Accuracy mean:",scores2.mean())

Accuracy mean: 0.9316400580551525


In [142]:
input_data=np.array(test['CONTENT'])

input_tc=count_vectorizer.transform(input_data)
type(input_tc)
print(input_tc)

  (0, 326)	1
  (0, 508)	1
  (0, 514)	1
  (0, 553)	1
  (0, 618)	1
  (0, 650)	1
  (0, 680)	1
  (0, 818)	1
  (0, 964)	1
  (0, 1034)	2
  (0, 1040)	1
  (0, 1084)	1
  (0, 1355)	1
  (0, 1392)	1
  (0, 1410)	1
  (0, 1447)	1
  (1, 326)	1
  (1, 680)	1
  (1, 730)	1
  (1, 1090)	1
  (1, 1203)	1
  (1, 1291)	1
  (1, 1304)	1
  (2, 326)	1
  (2, 492)	1
  :	:
  (84, 1463)	1
  (85, 310)	1
  (85, 327)	1
  (85, 963)	1
  (85, 988)	1
  (85, 989)	1
  (85, 1304)	1
  (86, 169)	1
  (86, 1034)	1
  (86, 1250)	1
  (86, 1287)	1
  (86, 1313)	1
  (86, 1355)	1
  (86, 1459)	1
  (87, 249)	1
  (87, 543)	1
  (87, 597)	1
  (87, 730)	1
  (87, 756)	1
  (87, 981)	1
  (87, 1085)	1
  (87, 1275)	1
  (87, 1291)	1
  (87, 1313)	1
  (87, 1426)	1


In [143]:
input_tfidf=tfidf.transform(input_tc)
type(input_tfidf)
print(input_tfidf)

  (0, 1447)	0.14990928316168292
  (0, 1410)	0.25278429383866213
  (0, 1392)	0.24548795589309308
  (0, 1355)	0.2990818079170654
  (0, 1084)	0.2833624659688231
  (0, 1040)	0.26120729784133545
  (0, 1034)	0.3465308176328071
  (0, 964)	0.2990818079170654
  (0, 818)	0.21895914473091682
  (0, 680)	0.1548801055597146
  (0, 650)	0.21490978376293218
  (0, 618)	0.24548795589309308
  (0, 553)	0.1790224515106302
  (0, 514)	0.2990818079170654
  (0, 508)	0.2990818079170654
  (0, 326)	0.12855181340371521
  (1, 1304)	0.3163486485650894
  (1, 1291)	0.29895789522807176
  (1, 1203)	0.38566307079776135
  (1, 1090)	0.5697785181492199
  (1, 730)	0.32711818526363057
  (1, 680)	0.36915528484202803
  (1, 326)	0.30640204642494295
  (2, 1403)	0.4822452844362567
  (2, 1304)	0.27435629280270907
  :	:
  (84, 815)	0.5002497048170762
  (85, 1304)	0.2643475437624856
  (85, 989)	0.3565580534504964
  (85, 988)	0.5034691179425599
  (85, 963)	0.3222681239439832
  (85, 327)	0.5643714988495546
  (85, 310)	0.3565580534504964

In [144]:
predictions=classifier.predict(input_tfidf)

In [145]:
confusion_matrix=confusion_matrix(np.array(test['CLASS']),predictions)
confusion_matrix

array([[38,  1],
       [12, 37]])

In [146]:
df=pd.read_csv('Youtube01-Psy.csv')
df.head()

COMMENT_ID            AUTHOR  \
0  LZQPQhLyRh80UYxNuaDWhIGQYNQ96IuCg-AYWqNPjpU         Julius NM   
1  LZQPQhLyRh_C2cTtd9MvFRJedxydaVW-2sNg5Diuo4A       adam riyati   
2  LZQPQhLyRh9MSZYnf8djyk0gEF9BHDPYrrK-qCczIY8  Evgeny Murashkin   
3          z13jhp0bxqncu512g22wvzkasxmvvzjaz04   ElNino Melendez   
4          z13fwbwp1oujthgqj04chlngpvzmtt3r3dw            GsMega   

                  DATE                                            CONTENT  \
0  2013-11-07T06:20:48  Huh, anyway check out this you[tube] channel: ...   
1  2013-11-07T12:37:15  Hey guys check out my new channel and our firs...   
2  2013-11-08T17:34:21             just for test I have to say murdev.com   
3  2013-11-09T08:28:43   me shaking my sexy ass on my channel enjoy ^_^    
4  2013-11-10T16:05:38            watch?v=vtaRGgvGtWQ   Check this out .   

   CLASS  
0      1  
1      1  
2      1  
3      1  
4      1

In [147]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 350 entries, 0 to 349
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   COMMENT_ID  350 non-null    object
 1   AUTHOR      350 non-null    object
 2   DATE        350 non-null    object
 3   CONTENT     350 non-null    object
 4   CLASS       350 non-null    int64 
dtypes: int64(1), object(4)
memory usage: 13.8+ KB


In [148]:
df.isnull().sum()

COMMENT_ID    0
AUTHOR        0
DATE          0
CONTENT       0
CLASS         0
dtype: int64

In [149]:
data=df[['CONTENT','CLASS']]
data.head()

CONTENT  CLASS
0  Huh, anyway check out this you[tube] channel: ...      1
1  Hey guys check out my new channel and our firs...      1
2             just for test I have to say murdev.com      1
3   me shaking my sexy ass on my channel enjoy ^_^       1
4            watch?v=vtaRGgvGtWQ   Check this out .      1

In [150]:
len(data)
len(data.query('CLASS==1'))
len(data.query('CLASS==0'))

175

In [151]:
fracdata=data.sample(frac=1)

In [152]:
train=fracdata.sample(frac=0.75,random_state=26)
test=data.drop(train.index)

In [153]:
x_train=np.array(train['CONTENT'])
y_train=np.array(train['CLASS'])

In [154]:
count_vectorizer=CountVectorizer()
X_train=count_vectorizer.fit_transform(x_train)

In [155]:
print('\nDimensions of training data:',X_train.shape)


Dimensions of training data: (262, 1111)


In [156]:
tfidf=TfidfTransformer()
train_tfidf=tfidf.fit_transform(X_train)
classifier=MultinomialNB().fit(train_tfidf,y_train)

In [157]:
scores=cross_val_score(classifier,X_train,y_train,cv=5)
scores

array([0.96226415, 0.94339623, 0.98076923, 0.92307692, 0.96153846])

In [158]:
scores2=cross_val_score(classifier,X_train,y_train)
print("Accuracy mean:",scores2.mean())

Accuracy mean: 0.9542089985486213


In [159]:
input_data=np.array(test['CONTENT'])

input_tc=count_vectorizer.transform(input_data)
type(input_tc)
print(input_tc)

  (0, 139)	1
  (0, 217)	1
  (0, 332)	1
  (0, 616)	1
  (0, 656)	2
  (0, 694)	1
  (0, 825)	1
  (1, 135)	1
  (1, 198)	1
  (1, 219)	1
  (1, 506)	1
  (1, 509)	1
  (1, 533)	1
  (1, 694)	2
  (1, 860)	1
  (1, 929)	1
  (1, 952)	1
  (1, 1014)	1
  (1, 1030)	1
  (2, 238)	1
  (2, 481)	1
  (2, 574)	1
  (2, 740)	1
  (3, 6)	1
  (3, 84)	1
  :	:
  (85, 243)	1
  (85, 357)	1
  (85, 481)	1
  (85, 574)	1
  (85, 740)	1
  (85, 754)	1
  (85, 1082)	1
  (86, 107)	1
  (86, 116)	1
  (86, 133)	1
  (86, 152)	1
  (86, 506)	1
  (86, 689)	1
  (86, 719)	1
  (86, 876)	1
  (86, 943)	1
  (86, 1084)	1
  (86, 1089)	1
  (87, 31)	1
  (87, 306)	1
  (87, 500)	1
  (87, 680)	1
  (87, 943)	1
  (87, 1037)	1
  (87, 1058)	1


In [160]:
input_tfidf=tfidf.transform(input_tc)
type(input_tfidf)
print(input_tfidf)

  (0, 825)	0.4490248530168538
  (0, 694)	0.2718704358046526
  (0, 656)	0.43645047366567613
  (0, 616)	0.24986325968450598
  (0, 332)	0.4254247040910842
  (0, 217)	0.24073880667082515
  (0, 139)	0.4822873947317529
  (1, 1030)	0.38174976127730026
  (1, 1014)	0.2010927171932024
  (1, 952)	0.16206256021948878
  (1, 929)	0.16511755486952306
  (1, 860)	0.3461224528424594
  (1, 694)	0.4622749643788031
  (1, 533)	0.2494359624096214
  (1, 509)	0.22352142560433635
  (1, 506)	0.20467014544809653
  (1, 219)	0.1944453506264376
  (1, 198)	0.3226553447019402
  (1, 135)	0.3616855016756538
  (2, 740)	0.5012730172298818
  (2, 574)	0.5012730172298818
  (2, 481)	0.5471886984390439
  (2, 238)	0.4450115197330137
  (3, 1056)	0.29419323692340593
  (3, 1030)	0.31051340859557125
  :	:
  (85, 740)	0.23388972558632234
  (85, 574)	0.23388972558632234
  (85, 481)	0.255313591840817
  (85, 357)	0.29799197887115253
  (85, 243)	0.31231745821712087
  (85, 238)	0.20763858946226607
  (85, 113)	0.6095919637254698
  (86, 10

In [161]:
df=pd.read_csv('Youtube03-LMFAO.csv')
df.head()

COMMENT_ID        AUTHOR  \
0  z13uwn2heqndtr5g304ccv5j5kqqzxjadmc0k  Corey Wilson   
1  z124jvczaz3dxhnbc04cffk43oiugj25yzo0k   Epic Gaming   
2      z13tczjy5xj0vjmu5231unho1ofey5zdk     LaS Music   
3  z13tzr0hdpnayhqqc04cd3zqqqjkf3ngckk0k    Cheryl Fox   
4  z12pcvix4zedcjvyb04ccr1r0mr2g5xwyng0k    PATRICK_TW   

                         DATE  \
0  2015-05-28T21:39:52.376000   
1  2015-05-28T20:07:20.610000   
2  2015-05-28T19:23:35.355000   
3  2015-05-28T17:49:35.294000   
4  2015-05-28T16:28:26.818000   

                                             CONTENT  CLASS  
0  <a href="http://www.youtube.com/watch?v=KQ6zr6...      0  
1                                   wierd but funny      0  
2  Hey guys, I&#39;m a human.<br /><br /><br />Bu...      1  
3       Party Rock....lol...who wants to shuffle!!!      0  
4                                        Party rock      0

In [162]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 438 entries, 0 to 437
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   COMMENT_ID  438 non-null    object
 1   AUTHOR      438 non-null    object
 2   DATE        438 non-null    object
 3   CONTENT     438 non-null    object
 4   CLASS       438 non-null    int64 
dtypes: int64(1), object(4)
memory usage: 17.2+ KB


In [163]:
df.isnull().sum()

COMMENT_ID    0
AUTHOR        0
DATE          0
CONTENT       0
CLASS         0
dtype: int64

In [164]:
data=df[['CONTENT','CLASS']]
data.head()

CONTENT  CLASS
0  <a href="http://www.youtube.com/watch?v=KQ6zr6...      0
1                                   wierd but funny      0
2  Hey guys, I&#39;m a human.<br /><br /><br />Bu...      1
3       Party Rock....lol...who wants to shuffle!!!      0
4                                        Party rock      0

In [165]:
len(data)
len(data.query('CLASS==1'))
len(data.query('CLASS==0'))

202

In [166]:
fracdata=data.sample(frac=1)

In [167]:
train=fracdata.sample(frac=0.75,random_state=26)
test=data.drop(train.index)

In [168]:
x_train=np.array(train['CONTENT'])
y_train=np.array(train['CLASS'])

In [169]:
count_vectorizer=CountVectorizer()
X_train=count_vectorizer.fit_transform(x_train)

In [170]:
print('\nDimensions of training data:',X_train.shape)


Dimensions of training data: (328, 806)


In [171]:
tfidf=TfidfTransformer()
train_tfidf=tfidf.fit_transform(X_train)
classifier=MultinomialNB().fit(train_tfidf,y_train)

In [172]:
scores=cross_val_score(classifier,X_train,y_train,cv=5)
scores

array([0.90909091, 0.89393939, 0.83333333, 0.96923077, 0.98461538])

In [173]:
scores2=cross_val_score(classifier,X_train,y_train)
print("Accuracy mean:",scores2.mean())

Accuracy mean: 0.9180419580419581


In [174]:
input_data=np.array(test['CONTENT'])

input_tc=count_vectorizer.transform(input_data)
type(input_tc)
print(input_tc)

  (0, 28)	2
  (0, 73)	1
  (0, 100)	2
  (0, 122)	9
  (0, 130)	1
  (0, 134)	1
  (0, 146)	1
  (0, 151)	1
  (0, 157)	1
  (0, 207)	1
  (0, 221)	1
  (0, 260)	1
  (0, 266)	1
  (0, 280)	2
  (0, 303)	1
  (0, 311)	1
  (0, 317)	1
  (0, 319)	1
  (0, 333)	1
  (0, 348)	1
  (0, 350)	1
  (0, 358)	1
  (0, 359)	1
  (0, 404)	1
  (0, 432)	1
  :	:
  (106, 711)	1
  (106, 747)	2
  (107, 427)	1
  (107, 433)	1
  (107, 437)	1
  (107, 632)	1
  (107, 800)	1
  (108, 63)	1
  (108, 90)	1
  (108, 134)	1
  (108, 145)	1
  (108, 237)	1
  (108, 296)	1
  (108, 380)	1
  (108, 420)	1
  (108, 462)	2
  (108, 500)	1
  (108, 534)	1
  (108, 662)	1
  (108, 711)	1
  (108, 742)	1
  (108, 799)	1
  (109, 427)	1
  (109, 632)	1
  (109, 700)	1


In [175]:
input_tfidf=tfidf.transform(input_tc)
type(input_tfidf)
print(input_tfidf)

  (0, 799)	0.06780252946360385
  (0, 774)	0.0936283446388529
  (0, 748)	0.21119036565176805
  (0, 711)	0.2510271811024594
  (0, 700)	0.03648586971066745
  (0, 687)	0.18827038582684458
  (0, 632)	0.06484674682473371
  (0, 627)	0.07951645567495645
  (0, 603)	0.12425008531918966
  (0, 569)	0.11013819635529319
  (0, 540)	0.12425008531918966
  (0, 535)	0.10559518282588402
  (0, 505)	0.043037751888943376
  (0, 503)	0.12425008531918966
  (0, 501)	0.11013819635529319
  (0, 496)	0.04322714071721949
  (0, 481)	0.11013819635529319
  (0, 462)	0.24344621272660324
  (0, 460)	0.08954285940268399
  (0, 453)	0.12425008531918966
  (0, 437)	0.07951645567495645
  (0, 432)	0.1159951594609695
  (0, 404)	0.06656826355941214
  (0, 359)	0.07202989089919028
  (0, 358)	0.10559518282588402
  :	:
  (106, 159)	0.16793098473410195
  (106, 97)	0.1798819819543296
  (107, 800)	0.4666138341289435
  (107, 632)	0.33792073838744213
  (107, 437)	0.4143655731606385
  (107, 433)	0.5739375135908308
  (107, 427)	0.4086294245885

In [176]:
predictions=classifier.predict(input_tfidf)

In [177]:
df=pd.read_csv('Youtube04-Eminem.csv')
df.head()

COMMENT_ID         AUTHOR  \
0    z12rwfnyyrbsefonb232i5ehdxzkjzjs2    Lisa Wellas   
1  z130wpnwwnyuetxcn23xf5k5ynmkdpjrj04   jason graham   
2    z13vsfqirtavjvu0t22ezrgzyorwxhpf3     Ajkal Khan   
3  z12wjzc4eprnvja4304cgbbizuved35wxcs  Dakota Taylor   
4    z13xjfr42z3uxdz2223gx5rrzs3dt5hna    Jihad Naser   

                         DATE  \
0                         NaN   
1  2015-05-29T02:26:10.652000   
2                         NaN   
3  2015-05-29T02:13:07.810000   
4                         NaN   

                                             CONTENT  CLASS  
0          +447935454150 lovely girl talk to me xxx      1  
1    I always end up coming back to this song<br />      0  
2  my sister just received over 6,500 new <a rel=...      1  
3                                              Cool      0  
4                     Hello I&#39;am from Palastine      1

In [178]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 448 entries, 0 to 447
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   COMMENT_ID  448 non-null    object
 1   AUTHOR      448 non-null    object
 2   DATE        203 non-null    object
 3   CONTENT     448 non-null    object
 4   CLASS       448 non-null    int64 
dtypes: int64(1), object(4)
memory usage: 17.6+ KB


In [179]:
df.isnull().sum()

COMMENT_ID      0
AUTHOR          0
DATE          245
CONTENT         0
CLASS           0
dtype: int64

In [180]:
data=df[['CONTENT','CLASS']]
data.head()

CONTENT  CLASS
0          +447935454150 lovely girl talk to me xxx      1
1    I always end up coming back to this song<br />      0
2  my sister just received over 6,500 new <a rel=...      1
3                                              Cool      0
4                     Hello I&#39;am from Palastine      1

In [181]:
len(data)
len(data.query('CLASS==1'))
len(data.query('CLASS==0'))

203

In [182]:
fracdata=data.sample(frac=1)

In [183]:
train=fracdata.sample(frac=0.75,random_state=26)
test=data.drop(train.index)

In [184]:
x_train=np.array(train['CONTENT'])
y_train=np.array(train['CLASS'])

In [185]:
count_vectorizer=CountVectorizer()
X_train=count_vectorizer.fit_transform(x_train)

In [186]:
print('\nDimensions of training data:',X_train.shape)


Dimensions of training data: (336, 1370)


In [187]:
tfidf=TfidfTransformer()
train_tfidf=tfidf.fit_transform(X_train)
classifier=MultinomialNB().fit(train_tfidf,y_train)

In [188]:
scores=cross_val_score(classifier,X_train,y_train,cv=5)
scores

array([0.91176471, 0.8358209 , 0.8358209 , 0.92537313, 0.94029851])

In [189]:
scores2=cross_val_score(classifier,X_train,y_train)
print("Accuracy mean:",scores2.mean())

Accuracy mean: 0.8898156277436348


In [190]:
input_data=np.array(test['CONTENT'])

input_tc=count_vectorizer.transform(input_data)
type(input_tc)
print(input_tc)

  (0, 42)	1
  (0, 103)	1
  (0, 181)	1
  (0, 530)	1
  (0, 622)	1
  (0, 647)	1
  (0, 921)	1
  (0, 1082)	1
  (0, 1184)	1
  (0, 1254)	1
  (0, 1257)	1
  (0, 1275)	1
  (0, 1333)	1
  (1, 103)	1
  (1, 181)	1
  (2, 54)	1
  (2, 476)	1
  (2, 542)	1
  (2, 747)	1
  (2, 907)	1
  (3, 139)	1
  (3, 701)	1
  (3, 849)	1
  (3, 1151)	1
  (3, 1184)	1
  :	:
  (111, 844)	1
  (111, 849)	1
  (111, 857)	1
  (111, 865)	1
  (111, 885)	1
  (111, 958)	1
  (111, 973)	1
  (111, 1030)	1
  (111, 1082)	1
  (111, 1095)	1
  (111, 1110)	1
  (111, 1128)	1
  (111, 1171)	2
  (111, 1179)	1
  (111, 1181)	2
  (111, 1192)	7
  (111, 1196)	1
  (111, 1215)	1
  (111, 1245)	4
  (111, 1276)	1
  (111, 1295)	1
  (111, 1296)	2
  (111, 1313)	1
  (111, 1331)	2
  (111, 1356)	6


In [191]:
input_tfidf=tfidf.transform(input_tc)
type(input_tfidf)
print(input_tfidf)

  (0, 1333)	0.38129319784556276
  (0, 1275)	0.32427033395729943
  (0, 1257)	0.2518848039046152
  (0, 1254)	0.17504383738517104
  (0, 1184)	0.12860256040687854
  (0, 1082)	0.20874867259096605
  (0, 921)	0.38129319784556276
  (0, 647)	0.23496174803899822
  (0, 622)	0.16276170927931766
  (0, 530)	0.3129240472872452
  (0, 181)	0.3381570665319136
  (0, 103)	0.35606017860089434
  (0, 42)	0.17067486611061394
  (1, 181)	0.6886423028909724
  (1, 103)	0.7251012196024897
  (2, 907)	0.3016802943437254
  (2, 747)	0.32924132564304237
  (2, 542)	0.5070953534058867
  (2, 476)	0.4020670224333537
  (2, 54)	0.6178879846050022
  (3, 1361)	0.31504371820660265
  (3, 1254)	0.29406422222187045
  (3, 1184)	0.21604537735639
  (3, 1151)	0.4833054374567635
  (3, 849)	0.27986659420794674
  :	:
  (111, 857)	0.08497396574304993
  (111, 849)	0.053457993993064896
  (111, 844)	0.12235339257729257
  (111, 833)	0.10041437670786695
  (111, 828)	0.08082745894900152
  (111, 690)	0.12235339257729257
  (111, 675)	0.1004143767

In [192]:
predictions=classifier.predict(input_tfidf)

In [193]:
df=pd.read_csv('Youtube05-Shakira.csv')
df.head()

COMMENT_ID                              AUTHOR  \
0    z13lgffb5w3ddx1ul22qy1wxspy5cpkz504                          dharma pal   
1      z123dbgb0mqjfxbtz22ucjc5jvzcv3ykj                       Tiza Arellano   
2  z12quxxp2vutflkxv04cihggzt2azl34pms0k  Prìñçeśś Âliś Łøvê Dømíñø Mâđiś™    
3      z12icv3ysqvlwth2c23eddlykyqut5z1h                       Eric Gonzalez   
4      z133stly3kete3tly22petvwdpmghrlli                       Analena López   

                         DATE  \
0  2015-05-29T02:30:18.971000   
1  2015-05-29T00:14:48.748000   
2  2015-05-28T21:00:08.607000   
3  2015-05-28T20:47:12.193000   
4  2015-05-28T17:08:29.827000   

                                             CONTENT  CLASS  
0                                         Nice song      0  
1                                      I love song       0  
2                                      I love song       0  
3  860,000,000 lets make it first female to reach...      0  
4                      shakira is best for worldcup      0

In [194]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 370 entries, 0 to 369
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   COMMENT_ID  370 non-null    object
 1   AUTHOR      370 non-null    object
 2   DATE        370 non-null    object
 3   CONTENT     370 non-null    object
 4   CLASS       370 non-null    int64 
dtypes: int64(1), object(4)
memory usage: 14.6+ KB


In [195]:
df.isnull().sum()

COMMENT_ID    0
AUTHOR        0
DATE          0
CONTENT       0
CLASS         0
dtype: int64

In [196]:
data=df[['CONTENT','CLASS']]
data.head()

CONTENT  CLASS
0                                         Nice song      0
1                                      I love song       0
2                                      I love song       0
3  860,000,000 lets make it first female to reach...      0
4                      shakira is best for worldcup      0

In [197]:
len(data)
len(data.query('CLASS==1'))
len(data.query('CLASS==0'))

196

In [198]:
fracdata=data.sample(frac=1)

In [199]:
train=fracdata.sample(frac=0.75,random_state=26)
test=data.drop(train.index)

In [200]:
x_train=np.array(train['CONTENT'])
y_train=np.array(train['CLASS'])

In [201]:
count_vectorizer=CountVectorizer()
X_train=count_vectorizer.fit_transform(x_train)

In [202]:
print('\nDimensions of training data:',X_train.shape)


Dimensions of training data: (278, 1172)


In [203]:
tfidf=TfidfTransformer()
train_tfidf=tfidf.fit_transform(X_train)
classifier=MultinomialNB().fit(train_tfidf,y_train)

In [204]:
scores=cross_val_score(classifier,X_train,y_train,cv=5)
scores

array([0.875     , 0.91071429, 0.91071429, 0.92727273, 0.94545455])

In [205]:
scores2=cross_val_score(classifier,X_train,y_train)
print("Accuracy mean:",scores2.mean())

Accuracy mean: 0.9138311688311689


In [206]:
input_data=np.array(test['CONTENT'])

input_tc=count_vectorizer.transform(input_data)
type(input_tc)
print(input_tc)

  (0, 687)	1
  (0, 916)	1
  (1, 597)	1
  (1, 916)	1
  (2, 148)	1
  (2, 372)	1
  (2, 528)	1
  (2, 877)	1
  (3, 94)	1
  (3, 427)	1
  (3, 657)	1
  (3, 867)	1
  (3, 877)	1
  (3, 912)	1
  (3, 916)	1
  (3, 1041)	1
  (4, 167)	1
  (4, 597)	1
  (4, 877)	1
  (4, 916)	1
  (4, 1005)	1
  (4, 1079)	2
  (5, 426)	1
  (6, 21)	1
  (6, 468)	1
  :	:
  (88, 724)	16
  (89, 75)	1
  (89, 118)	1
  (89, 137)	1
  (89, 530)	1
  (89, 597)	1
  (89, 893)	1
  (89, 916)	1
  (89, 993)	1
  (89, 1005)	1
  (89, 1012)	1
  (89, 1095)	1
  (90, 46)	1
  (90, 64)	2
  (90, 136)	1
  (90, 372)	1
  (90, 508)	1
  (90, 528)	1
  (90, 530)	1
  (90, 597)	1
  (90, 916)	1
  (90, 1005)	1
  (90, 1040)	1
  (90, 1087)	1
  (91, 1144)	1


In [207]:
input_tfidf=tfidf.transform(input_tc)
type(input_tfidf)
print(input_tfidf)

  (0, 916)	0.5131807435146195
  (0, 687)	0.8582805628032026
  (1, 916)	0.6636048033810807
  (1, 597)	0.748083327530802
  (2, 877)	0.4768649427225943
  (2, 528)	0.43726573063337004
  (2, 372)	0.491052288384049
  (2, 148)	0.5833233728290258
  (3, 1041)	0.45897270529613804
  (3, 916)	0.214708300196901
  (3, 912)	0.43510721146782194
  (3, 877)	0.2575718670446174
  (3, 867)	0.36783416276733466
  (3, 657)	0.40147068711757833
  (3, 427)	0.3886826740631159
  (3, 94)	0.20006984886605764
  (4, 1079)	0.7922727832469986
  (4, 1005)	0.1973911695391373
  (4, 916)	0.24218944290319047
  (4, 877)	0.2905392429163803
  (4, 597)	0.2730207548479829
  (4, 167)	0.3401932577346034
  (5, 426)	1.0
  (6, 1115)	0.49684818543506565
  (6, 1092)	0.42018054740264477
  :	:
  (88, 203)	0.3132671199654752
  (89, 1095)	0.3650964155217665
  (89, 1012)	0.3066331731948997
  (89, 1005)	0.17791851925430296
  (89, 993)	0.2046638604074733
  (89, 916)	0.21829744036151846
  (89, 893)	0.4423806180718597
  (89, 597)	0.2460872416008

In [208]:
predictions=classifier.predict(input_tfidf)